# Generated by Django 5.1.5 on 2025-01-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_contact_number_customuser_employee_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_specialty',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('aesthetic_medicine', 'Aesthetic Medicine'), ('dermatologist', 'Dermatologist'), ('plastic_surgery', 'Plastic Surgery')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
