# Generated by Django 5.1.5 on 2025-01-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_employee_type_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_specialty',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('aesthetic_medicine', 'Aesthetic Medicine'), ('plastic_surgery', 'Plastic Surgery'), ('dermatology', 'Dermatology'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
