# Generated by Django 5.1.5 on 2025-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_company_phone_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='company_phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_specialty',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('aesthetic_medicine', 'Aesthetic Medicine'), ('dermatologist', 'Dermatologist'), ('plastic_surgery', 'Plastic Surgery'), ('dermatology', 'Dermatology')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=10),
        ),
    ]
